### PR TITLE
Denite

### PR DESCRIPTION
**Pull request by octaltree**
Hello. Your plug-in is useful. I thought it would be easier to use if it supported not only unite but also denite.

:Denite rust/doc
:Denite rust/doc:modules
implemented.
I want you to consider.

### CODE REVIEW

**Comment by rhysd** [comment]
Looks good.

I'm not denite.nvim user. So I'm not understanding how to use this. Would you add instruction for how to use this source in ['Usage' section](https://github.com/rhysd/rust-doc.vim#usage) like 'unite.vim source' item and [help doc](https://github.com/rhysd/rust-doc.vim/blob/master/doc/rust-doc.txt#L122)?

**Review by rhysd — APPROVED** [review]
OK, looks good :tada: Thank you for adding this. (though I could not review Python code of denite source since I'm not familiar with it).

**Comment by octaltree** [comment]
Thank you for accept. I'll "watch" this repo even though this is the first time I wrote denite source.

**Comment by rhysd** [comment]
Thanks. I'll ping you when I have an issue related to this feature.

**Pull request merged**
